name: Feature request
description: Suggest an idea for this project
title: "Feature Request - ISSUE-NAME-HERE"
labels:
  - enhancement
projects:
  - splk3/1
assignees:
  - splk3
body:
  - type: textarea
    id: feature_request
    attributes:
      label: What is the feature or resource you would like to see added?
      description: A clear and concise description of the feature request and how you would like it to be implemented.
      placeholder: It would be helpful if I could...I would implement this by...
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Add any other information or screenshots about the feature request here.
