rules:
  excessive-permissions:
    ignore:
      - .github/workflows/deploy.yml
  impostor-commit:
    ignore:
      - .github/workflows/update-docs-agent.lock.yml
  artipacked:
    ignore:
      - .github/workflows/update-docs-agent.lock.yml
