export const DRILL_PDF_PAGE_HEIGHT_MM = 297;
export const DRILL_PDF_MARGIN_MM = 20;
export const DRILL_PDF_HEADER_START_Y_MM = 15;
export const DRILL_PDF_HEADER_LOGO_HEIGHT_MM = 16;
export const DRILL_PDF_HEADER_LOGO_BOTTOM_GAP_MM = 4;
export const DRILL_PDF_HEADER_SEPARATOR_BOTTOM_GAP_MM = 8;
export const DRILL_PDF_TAGS_HEIGHT_MM = 12;
export const DRILL_PDF_NEW_PAGE_TOP_GAP_MM = 5;
export const DRILL_PDF_FOOTER_LOGO_HEIGHT_MM = 16;
export const DRILL_PDF_FOOTER_SEPARATOR_GAP_MM = 4;
export const DRILL_PDF_FOOTER_CONTENT_GAP_MM = 8;

export const SKILLS_FOCUS_TOP_GAP = 4;
export const SKILLS_FOCUS_LABEL_TO_VALUES_GAP = 4;
export const PROGRESSION_TEXT_FONT_SIZE = 10;
export const PROGRESSION_TEXT_LINE_HEIGHT = 4;
export const PROGRESSION_IMAGE_TEXT_GAP = 4;
export const PROGRESSION_VIDEO_NOTE_HEIGHT = 10;
export const SINGLE_COLUMN_DRILL_IMAGE_WIDTH_RATIO = 0.75;

export const DRILL_VIDEO_SECTION_TOP_GAP_MM = 3;
export const DRILL_VIDEO_SEPARATOR_TITLE_SPACING_MM = 8;
export const DRILL_VIDEO_QR_SIZE_MM = 9;
export const DRILL_VIDEO_QR_GAP_MM = 2;
export const DRILL_VIDEO_QR_FLOW_CLEARANCE_MM = 4;
